# Generated by Django 5.0.2 on 2024-05-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, verbose_name='Стоимость'),
        ),
    ]
