# Generated by Django 5.0.2 on 2024-05-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_plant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.FloatField(blank=True, verbose_name='Стоимость'),
        ),
    ]
