# Generated by Django 5.0.2 on 2024-05-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_plant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total_quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
