# Generated by Django 5.0.2 on 2024-06-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default=1, max_length=20, verbose_name='Адрес эл почты'),
            preserve_default=False,
        ),
    ]
