# Generated by Django 5.0.2 on 2024-06-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_phone_number_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default=('В обработке',), max_length=50, verbose_name='Статус заказа'),
        ),
    ]
