# Generated by Django 5.0.2 on 2024-06-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'В обработке'), ('2', 'Оформлен'), ('3', 'Собран'), ('4', 'Доставлен'), ('5', 'Закрыт')], default=('1', 'В обработке'), max_length=50, verbose_name='Статус заказа'),
        ),
    ]
